# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmoiseye <mirror12k@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/01/28 08:52:20 by nmoiseye          #+#    #+#              #
#    Updated: 2017/01/28 11:05:44 by nmoiseye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = eval_expr
SRCS = eval_expr.c util.c

all: build

build:
	gcc -Wall -Wextra -Werror $(SRCS) -o $(NAME)
