# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmoiseye <mirror12k@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/01/25 15:59:32 by nmoiseye          #+#    #+#              #
#    Updated: 2017/01/25 18:39:27 by nmoiseye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_tail
SRCS = ft_tail.c

all: build

build:
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRCS)

clean:

fclean: clean
	rm -f $(NAME)
