# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmoiseye <mirror12k@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/01/23 11:30:00 by nmoiseye          #+#    #+#              #
#    Updated: 2017/01/23 11:41:48 by nmoiseye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: build

build:
	gcc -Wall -Wextra -Werror doop_ops.c doop.c -o do-op

clean:
	rm do-op

