# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmoiseye <mirror12k@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/01/28 12:06:22 by nmoiseye          #+#    #+#              #
#    Updated: 2017/01/28 15:52:03 by nmoiseye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2
SRCS = rush02.c damn_util.c

all: build

build:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS)

fclean:
	rm -f $(NAME)


