# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmoiseye <mirror12k@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/01/25 13:46:11 by nmoiseye          #+#    #+#              #
#    Updated: 2017/01/25 15:34:07 by nmoiseye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = ft_display_file

SRCS = ft_display_file.c

all: build


build:
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRCS)
clean:

fclean: clean
	rm -f $(NAME)
